import type { Metadata } from 'next'
import '../globals.css'
import { AppThemeProvider, useAppThemeContext } from '../components/shared/contexts/ThemeContext'
import { Button } from '@mui/material';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { toggleTheme } = useAppThemeContext();

  return (
    <html lang="pt-Br">
      <body>
        <AppThemeProvider>
          <Button onClick={toggleTheme}>trocar theme</Button>

          {children}
        </AppThemeProvider>
      </body>
    </html>
  )
}
