import { Metadata } from 'next'
import '../globals.css'
import { Button } from '@mui/material';
import { AppThemeProvider, useAppThemeContext } from '../shared/contexts';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode;
}


export default function RootLayout({ children }: RootLayoutProps) {

  const { toggleTheme } = useAppThemeContext();

  return (
    <html lang="pt-Br">
      <body>
        <AppThemeProvider>
          <Button onClick={toggleTheme}>Trocar tema</Button>
          {children}
        </AppThemeProvider>
      </body>
    </html>
  );
}
